CREATE DATABASE BUDDIES;
-- DROP DATABASE BUDDIES;

USE BUDDIES;

CREATE TABLE Utilizador (
	Nr INT NOT NULL AUTO_INCREMENT,
    Nome VARCHAR(100) NOT NULL,
    Email VARCHAR(100) NOT NULL UNIQUE,
    Pass VARCHAR(255) NOT NULL,
    PRIMARY KEY (Nr)
);

CREATE TABLE Pista (
	id INT NOT NULL AUTO_INCREMENT,
    Nome VARCHAR(100) NOT NULL,
    Morada_Localidade VARCHAR(45) NOT NULL,
    Morada_Rua VARCHAR(45) NOT NULL,
    Morada_CodigoPostal VARCHAR(45) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE Corrida (
	Nr INT NOT NULL,
    id INT NOT NULL,
    MelhorTempo TIME(2) NOT NULL,
    PRIMARY KEY (Nr, id),
    FOREIGN KEY (Nr)
		REFERENCES Utilizador(Nr),
    FOREIGN KEY (id)
		REFERENCES Pista(id)
);
